name: Sync EFS with GitHub repository

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install nfs-common
      run: sudo apt-get update && sudo apt-get install -y nfs-common
      
    - name: Sync EFS with repository
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ACCESS_POINT_ARN: ${{ secrets.ACCESS_POINT_ARN }}
      run: |
        sudo mkdir ~/efs
        sudo mount -t nfs -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 arn:aws:elasticfilesystem:eu-west-2:183663748910:access-point/fsap-0c174abd8b8f7ecd0:/ ~/efs
        rsync -av --delete ./ ~/efs/
        sudo umount ~/efs/
